const aspects = 
    [
        {
            id: 1,
            name: 'Compete',
            alternate: 'Challenge',
            image: "https://cdn.pixabay.com/photo/2013/02/19/02/24/football-83222_960_720.jpg",
            text: "Vestibulum porta erat. Vestibulum maximus placerat egestas.",
        },
        {
            id: 2,
            name: 'Control',
            alternate: 'Skill',
            image: "https://cdn.pixabay.com/photo/2020/05/17/06/42/football-5180297_960_720.jpg",
            text: "Maecenas efficitur, justo quis consequat porta.",
        },
        {
            id: 3,
            name: 'Crowd',
            alternate: 'Stadium',
            image: "https://cdn.pixabay.com/photo/2016/11/29/02/05/audience-1866738_960_720.jpg",
            text: "Ut vel eleifend nisi. Phasellus iaculis laoreet.",
        },
        {
            id: 4,
            name: 'Fan',
            alternate: 'Celebrate',
            image: "https://cdn.pixabay.com/photo/2016/03/27/20/57/people-1284253_960_720.jpg",
            text: "Sed a pellentesque justo, vitae cursus justo.",
        },
        {
            id: 5,
            name: 'Rest',
            alternate: 'Summer',
            image: "https://cdn.pixabay.com/photo/2017/05/31/10/19/rio-2359870_960_720.jpg",
            text: "Morbi pharetra scelerisque diam in consectetur.",
        },
        {
            id: 6,
            name: 'Grass Roots',
            alternate: 'Five-a-side',
            image: "https://cdn.pixabay.com/photo/2015/05/15/14/25/soccer-768482_960_720.jpg",
            text: "Morbi nec nulla aliquam, efficitur nibh ut, consequat libero.",
        },
        {
            id: 7,
            name: 'Resilience',
            alternate: 'Strength',
            image: "https://cdn.pixabay.com/photo/2015/03/30/12/48/fitness-698669_960_720.jpg",
            text: "Proin arcu metus, semper eget fermentum pellentesque.",
        },
        {
            id: 8,
            name: 'Identity',
            alternate: 'Separate',
            image: "https://cdn.pixabay.com/photo/2017/12/24/15/12/russia-3037142_960_720.png",
            text: "Class aptent taciti sociosqu ad litora torquent nostra.",
        },
        {
            id: 9,
            name: 'Place',
            alternate: 'Kick',
            image: "https://cdn.pixabay.com/photo/2018/06/12/20/17/football-3471402_960_720.jpg",
            text: "Nam elementum leo eget lectus tincidunt, odio feugiat.",
        },
        {
            id: 10,
            name: 'Pitch',
            alternate: 'Tactics',
            image: "https://cdn.pixabay.com/photo/2017/01/31/08/32/field-2023250_960_720.png",
            text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
        },
        {
            id: 11,
            name: 'Pressure',
            alternate: 'Penalty',
            image: "https://cdn.pixabay.com/photo/2017/08/07/06/54/people-2600808_960_720.jpg",
            text: "Vestibulum non tellus non velit dignissim porttitor non a eros.",
        },
        {
            id: 12,
            name: 'Team',
            alternate: 'Together',
            image: "https://cdn.pixabay.com/photo/2015/06/12/18/26/team-807300_960_720.jpg",
            text: "Vestibulum suscipit ex eu urna congue gravida.",
        },
        {
            id: 13,
            name: 'Reward',
            alternate: 'Jubilation',
            image: "https://cdn.pixabay.com/photo/2012/04/26/10/31/world-41953_960_720.png",
            text: "Nam interdum turpis id libero semper eleifend.",
        },
    ];
  
  export default aspects;